<Project Sdk="Godot.NET.Sdk/4.5.1">
    <PropertyGroup>
        <!-- 如果你安装了10.0并遇到问题，改下这里 -->
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>


        <!-- 改成你的杀戮尖塔2目录 -->
        <Sts2Dir>E:\Games\SlayTheSpire\Slay.the.Spire.2</Sts2Dir>
        <Sts2DataDir>$(Sts2Dir)\data_sts2_windows_x86_64</Sts2DataDir>
        <GodotExe>D:\代码\Godot_v4.5.1-stable_mono_win64/Godot_v4.5.1-stable_mono_win64.exe</GodotExe>
        <RootNamespace>Diceomancer</RootNamespace>

        <!-- 其余省略，添加以下这行，可以自动部署到你的mods文件夹 -->
        <RitsuLibDeployDir>$(Sts2Dir)/mods/STS2-RitsuLib/</RitsuLibDeployDir>

        <ModsPath>$(Sts2Dir)\mods</ModsPath>
    </PropertyGroup>

    <!--    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">-->
    <!--        <Optimize>false</Optimize>-->
    <!--        <DebugType>portable</DebugType>-->
    <!--    </PropertyGroup>-->

    <!--    <PropertyGroup Condition="'$(Configuration)' == 'Release'">-->
    <!--        <Optimize>true</Optimize>-->
    <!--        <DebugType>none</DebugType>-->
    <!--        <PathMap>$(AppOutputBase)=.\</PathMap>-->
    <!--    </PropertyGroup>-->

<!--    <PropertyGroup>-->
<!--        &lt;!&ndash; 回退：手动安装到游戏 mods 目录（需要另外定义 ModsPath） &ndash;&gt;-->
<!--        <MultiEnchantmentModPath Condition="!Exists('$(MultiEnchantmentModPath)')">$(ModsPath)/MultiEnchantmentMod/MultiEnchantmentMod.dll</MultiEnchantmentModPath>-->
<!--    </PropertyGroup>-->

    <ItemGroup>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <!-- 本地引用，注意路径是否正确 -->
        <Reference Include="MultiEnchantmentMod">
            <HintPath>$(MultiEnchantmentModPath)</HintPath>
            <Private>false</Private>
        </Reference>
        <!-- NuGet获取，注意版本是否一致，不一致手动更改Version -->
        <PackageReference Include="STS2.RitsuLib" Version="0.4.60"/>
<!--        <PackageReference Include="STS2.RitsuLib" Version="*"/>-->


        <!--        <PackageReference Include="FuYnAloft.Sts2.MinionLib.RitsuAdapters" Version="0.4.4"/>-->
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Diceomancer\images\Character\fishing_bg.png"/>
        <Content Include="Diceomancer\images\Character\rest.png"/>
        <Content Include="Diceomancer\images\Encounters\city1_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\city1_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\city1_layer3.png" />
        <Content Include="Diceomancer\images\Encounters\city_palace_layer0.png" />
        <Content Include="Diceomancer\images\Encounters\city_palace_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer0.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer2_anim_0000.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer2_anim_0001.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer2_anim_0002.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer2_anim_0003.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer2_anim_0004.png" />
        <Content Include="Diceomancer\images\Encounters\city_ruins_layer3.png" />
        <Content Include="Diceomancer\images\Encounters\city_slum_layer0.png" />
        <Content Include="Diceomancer\images\Encounters\city_slum_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\forest_layer2_ground.png" />
        <Content Include="Diceomancer\images\Encounters\forest_layer3_variant1.png" />
        <Content Include="Diceomancer\images\Encounters\forest_layer3_variant2.png" />
        <Content Include="Diceomancer\images\Encounters\forest_original_layer3.png" />
        <Content Include="Diceomancer\images\Encounters\homerealm_layer0.png" />
        <Content Include="Diceomancer\images\Encounters\homerealm_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer0.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag1_0000.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag1_0001.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag1_0002.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag1_0003.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag1_0004.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag2_0000.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag2_0001.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag2_0002.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer1_flag2_0003.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_boneyard_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_ending_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_ending_layer3.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_ending_layer4.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_field_layer0.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_field_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_field_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_field_layer4.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_layer0-3.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_layer0-4.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_layer0-5.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_village_layer0_1.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_village_layer1_1.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_village_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_village_layer3.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_windmill_layer1.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_windmill_layer2.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_windmill_layer3.png" />
        <Content Include="Diceomancer\images\Encounters\riverside_windmill_layer4.png" />
        <Content Include="Diceomancer\images\Energy\D20_big.png" />
        <Content Include="Diceomancer\images\Energy\D20.png" />
        <Content Include="Diceomancer\images\Energy\ManaBlack.png" />
        <Content Include="Diceomancer\images\Energy\slot_unknown.png" />
        <Content Include="Diceomancer\images\Monsters\error.png" />
        <Content Include="Diceomancer\images\Monsters\error.png.import" />
        <Content Include="Diceomancer\images\Orbs\ManaBlack.png" />
        <Content Include="Diceomancer\images\Orbs\ManaBlue.png" />
        <Content Include="Diceomancer\images\Orbs\ManaGreen.png" />
        <Content Include="Diceomancer\images\Orbs\ManaPurple.png" />
        <Content Include="Diceomancer\images\Orbs\ManaRed.png" />
        <Content Include="Diceomancer\images\Orbs\ManaVoid.png" />
        <Content Include="Diceomancer\images\Potions\Bonfire.png" />
        <Content Include="Diceomancer\images\Potions\后悔药.png" />
        <Content Include="Diceomancer\images\Relics\ManaBlue.png" />
        <Content Include="Diceomancer\images\Relics\BuilderMana.png" />
        <Content Include="Diceomancer\images\Relics\ManaGreen.png" />
        <Content Include="Diceomancer\images\Relics\ManaRed.png" />
        <Content Include="Diceomancer\images\Relics\ManaRedBlue.png" />
        <Content Include="Diceomancer\images\Relics\ManaRedGreen.png" />
        <Content Include="Diceomancer\images\Relics\RedBall.png" />
        <Content Include="Diceomancer\images\Relics\ProRing.png" />
        <Content Include="Diceomancer\images\Relics\ManaP.png" />
        <Content Include="Diceomancer\images\Relics\ManaP.png.import" />
        <Content Include="Diceomancer\localization\zhs\encounters.json" />
        <Content Include="Diceomancer\localization\zhs\monsters.json" />
        <Content Include="Diceomancer\localization\zhs\orbs.json" />
        <Content Include="Diceomancer\localization\zhs\potions.json" />
        <Content Include="Scripts\Cards\Ancient\K.cs.uid" />
        <Content Include="Scripts\Cards\Ancient\NullCard.cs.uid" />
        <Content Include="Scripts\Cards\Event\InvincibleStrike.cs.uid" />
        <Content Include="Scripts\Cards\Event\StrikeSecret.cs.uid" />
        <Content Include="Scripts\Cards\Template\MiracleTemplate.cs.uid" />
        <Content Include="Scripts\Cards\Uncommon\Swarm.cs.uid" />
        <Content Include="Scripts\计划.txt" />
    </ItemGroup>


    <ItemGroup>
        <Compile Remove="Example\**" />
        <Compile Remove="Scripts\Hero\WonderfulCardPool\**" />
        <Compile Remove="参考\**" />
        <Compile Remove="示例\**" />
    </ItemGroup>


    <ItemGroup>
        <EmbeddedResource Remove="Example\**" />
        <EmbeddedResource Remove="Scripts\Hero\WonderfulCardPool\**" />
        <EmbeddedResource Remove="参考\**" />
        <EmbeddedResource Remove="示例\**" />
    </ItemGroup>


    <ItemGroup>
        <Folder Include="Diceomancer\images\Ancient\" />
        <Folder Include="Scripts\Cards\Token\Options\" />
        <Folder Include="Scripts\Cards\Token\Scrap\"/>
    </ItemGroup>


    <!-- 自动复制dll和json -->
    <Target Name="Copy Mod" AfterTargets="PostBuildEvent">
        <Message Text="Copying mod to Slay the Spire 2 mods folder..." Importance="high"/>
        <MakeDir Directories="$(Sts2Dir)/mods/"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/"/>
        <!-- 新增 -->
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb"
              DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/"
              Condition="Exists('$(TargetDir)$(TargetName).pdb')"/>
        <Copy SourceFiles="$(MSBuildProjectName).json" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/"/>
    </Target>

    <Target Name="ExportPck">
        <Message Text="Copying PCK to Slay the Spire 2 mods folder..." Importance="high"/>
        <Exec Command="&quot;$(GodotExe)&quot; --headless --export-pack &quot;MyMod.pck&quot; &quot;$(Sts2Dir)/mods/$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
              EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"
              ContinueOnError="WarnAndContinue"/>
    </Target>


</Project>