<Project Sdk="Godot.NET.Sdk/4.5.1">
    <PropertyGroup>
        <!-- 如果你安装了10.0并遇到问题，改下这里 -->
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>


        <!-- 改成你的杀戮尖塔2目录 -->
        <Sts2Dir>E:\Games\SlayTheSpire\Slay.the.Spire.2</Sts2Dir>
        <Sts2DataDir>$(Sts2Dir)\data_sts2_windows_x86_64</Sts2DataDir>
        <GodotExe>D:\代码\Godot_v4.5.1-stable_mono_win64/Godot_v4.5.1-stable_mono_win64.exe</GodotExe>
        <RootNamespace>Diceomancer</RootNamespace>

        <!-- 其余省略，添加以下这行，可以自动部署到你的mods文件夹 -->
        <RitsuLibDeployDir>$(Sts2Dir)/mods/STS2-RitsuLib/</RitsuLibDeployDir>

        <ModsPath>$(Sts2Dir)\mods</ModsPath>
    </PropertyGroup>

    <!--    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">-->
    <!--        <Optimize>false</Optimize>-->
    <!--        <DebugType>portable</DebugType>-->
    <!--    </PropertyGroup>-->

    <!--    <PropertyGroup Condition="'$(Configuration)' == 'Release'">-->
    <!--        <Optimize>true</Optimize>-->
    <!--        <DebugType>none</DebugType>-->
    <!--        <PathMap>$(AppOutputBase)=.\</PathMap>-->
    <!--    </PropertyGroup>-->

<!--    <PropertyGroup>-->
<!--        &lt;!&ndash; 回退：手动安装到游戏 mods 目录（需要另外定义 ModsPath） &ndash;&gt;-->
<!--        <MultiEnchantmentModPath Condition="!Exists('$(MultiEnchantmentModPath)')">$(ModsPath)/MultiEnchantmentMod/MultiEnchantmentMod.dll</MultiEnchantmentModPath>-->
<!--    </PropertyGroup>-->

    <ItemGroup>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <!-- 本地引用，注意路径是否正确 -->
        <Reference Include="MultiEnchantmentMod">
            <HintPath>$(MultiEnchantmentModPath)</HintPath>
            <Private>false</Private>
        </Reference>
        <!-- NuGet获取，注意版本是否一致，不一致手动更改Version -->
        <PackageReference Include="STS2.RitsuLib" Version="0.5.11"/>
<!--        <PackageReference Include="STS2.RitsuLib" Version="*"/>-->
        
        <!--        <PackageReference Include="FuYnAloft.Sts2.MinionLib.RitsuAdapters" Version="0.4.4"/>-->
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Scripts\Cards\Ancient\K.cs.uid" />
        <Content Include="Scripts\Cards\Ancient\NullCard.cs.uid" />
        <Content Include="Scripts\Cards\Builder\Uncommon\Swarm.cs.uid" />
        <Content Include="Scripts\Cards\Curse\Exhausted.cs.uid" />
        <Content Include="Scripts\Cards\Curse\Hallucination.cs.uid" />
        <Content Include="Scripts\Cards\Curse\Hesitation.cs.uid" />
        <Content Include="Scripts\Cards\Curse\Vertigo.cs.uid" />
        <Content Include="Scripts\Cards\Event\InvincibleStrike.cs.uid" />
        <Content Include="Scripts\Cards\Event\StrikeSecret.cs.uid" />
        <Content Include="Scripts\Cards\Template\KickTemplate.cs.uid" />
        <Content Include="Scripts\Cards\Template\MiracleTemplate.cs.uid" />
    </ItemGroup>


    <ItemGroup>
        <Compile Remove="Example\**" />
        <Compile Remove="Scripts\Hero\WonderfulCardPool\**" />
        <Compile Remove="示例\**" />
        <Compile Remove="Diceomancer\**" />
        <Compile Remove=".godot\**" />
        <Compile Remove="教程\**" />
        <Compile Remove="计划\**" />
    </ItemGroup>


    <ItemGroup>
        <EmbeddedResource Remove="Example\**" />
        <EmbeddedResource Remove="Scripts\Hero\WonderfulCardPool\**" />
        <EmbeddedResource Remove="示例\**" />
        <EmbeddedResource Remove="Diceomancer\**" />
        <EmbeddedResource Remove=".godot\**" />
        <EmbeddedResource Remove="教程\**" />
        <EmbeddedResource Remove="计划\**" />
    </ItemGroup>


    <ItemGroup>
        <Folder Include="Scripts\Cards\Builder\" />
        <Folder Include="Scripts\Cards\Token\Options\" />
        <Folder Include="Scripts\Cards\Token\Scrap\"/>
        <Folder Include="Scripts\Powers\MonstersPower\" />
        <Folder Include="Scripts\Relics\Common\" />
    </ItemGroup>


    <!-- 自动复制dll和json -->
    <Target Name="Copy Mod" AfterTargets="PostBuildEvent">
        <Message Text="Copying mod to Slay the Spire 2 mods folder..." Importance="high"/>
        <MakeDir Directories="$(Sts2Dir)/mods/"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/"/>
        <!-- 新增 -->
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb"
              DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/"
              Condition="Exists('$(TargetDir)$(TargetName).pdb')"/>
        <Copy SourceFiles="$(MSBuildProjectName).json" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/"/>
    </Target>

    <Target Name="ExportPck">
        <Message Text="Copying PCK to Slay the Spire 2 mods folder..." Importance="high"/>
        <Exec Command="&quot;$(GodotExe)&quot; --headless --export-pack &quot;MyMod.pck&quot; &quot;$(Sts2Dir)/mods/$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
              EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"
              ContinueOnError="WarnAndContinue"/>
    </Target>


</Project>